### ISSUE TITLE
"Edit this page" link not working

### ISSUE THREAD

**Issue by snehel4510** [paramsiddharth/rema#58]
The "edit this page" link on the documentation section of the webpage isn't working.

I didn't understood the link where it takes us - [edit this page](https://github.com/paramsiddharth/rema-docs/tree/main/packages/create-docusaurus/templates/shared/docs/home.md)
The ```rema-docs``` repo doesn't have any directory named ```tree``` while this link takes us to that place

Also I don't see any point of having this feature on the website itself.(Although the project is open-source and people can contribute via pull requests through the repo)
But the owner must need to have the credibility of having its own documentation since it is not a wikipedia but a software created by his own efforts.

**Comment by paramsiddharth** [comment]
To be noted, @snehel4510 ! I had already been looking into this issue. Must be an issue with the Docusaurus configuration. I'll try to fix it.

If you are interested in making a PR, please go ahead. :)

**Comment by snehel4510** [comment]
Sure I would love to, but first I need to learn about the Docusaurus itself😅

**Comment by paramsiddharth** [comment]
@snehel4510 Closing, fixed the bug. Turns out to be a small misconfiguration I overlooked. Thank you for the issue, Snehel! :)
